name: Deploy to Linode Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Linode CLI
        run: |
          pip3 install linode-cli --upgrade
          
      - name: Set Linode CLI token
        run: |
          echo "export LINODE_CLI_TOKEN=${{ secrets.LINODE_API_TOKEN }}" >> $GITHUB_ENV
          
      - name: Configure kubectl
        run: |
          echo "${{ secrets.LINODE_KUBECONFIG }}" > kubeconfig.yaml
          kubectl config view --raw > kubeconfig-merged.yaml
          kubectl config use-context --kubeconfig=kubeconfig-merged.yaml
        env:
          LINODE_CLI_TOKEN: ${{ secrets.LINODE_API_TOKEN }}
          
      - name: Apply Kubernetes deployment
        run: kubectl cluster-info

      - name: Apply Kubernetes service
        run: kubectl cluster-info
