name: Deploy to Linode Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Linode CLI
        run: |
          pip3 install linode-cli --upgrade
          
      - name: Set Linode CLI token
        run: |
          echo "export LINODE_CLI_TOKEN=${{ secrets.LINODE_API_TOKEN }}" >> $GITHUB_ENV
          
      - name: Configure kubectl
        uses: engineerd/setup-kubectl@v1
        with:
          version: latest
        env:
          KUBECONFIG: ${{ secrets.LINODE_KUBECONFIG }}
          
      - name: run
        run: kubectl cluster-info
