name: Deploy to Linode Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Linode CLI
        run: |
          pip3 install linode-cli --upgrade
          
      - name: Set Linode CLI token
        run: |
          echo "export LINODE_CLI_TOKEN=${{ secrets.LINODE_API_TOKEN }}" >> $GITHUB_ENV
          
      - uses: engineerd/setup-kind@v0.5.0
      - name: Testing
        run: |
              kubectl cluster-info
              kubectl get pods -n kube-system
              echo "current-context:" $(kubectl config current-context)
              echo "environment-kubeconfig:" ${KUBECONFIG}
