name: Deploy to Linode Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Linode CLI
        run: |
          pip3 install linode-cli --upgrade
          
      - name: Set Linode CLI token
        run: |
          echo "export LINODE_CLI_TOKEN=${{ secrets.LINODE_API_TOKEN }}" >> $GITHUB_ENV

      - name: Add linode context to kubeconfig files
        run: |
          kubectl config set-cluster linode --server=https://6685ec86-7c10-4c9e-91c6-45d7a64f8f85.ap-south-2.linodelke.net:443 --kubeconfig=kubeconfig.yaml
          kubectl config set-context linode --cluster=linode --user=default --kubeconfig=kubeconfig.yaml
          kubectl config use-context linode --kubeconfig=kubeconfig.yaml
          kubectl config view --raw > kubeconfig-merged.yaml
        env:
          export LINODE_CLI_TOKEN: ${{ secrets.LINODE_API_TOKEN }}

          
      - name: Configure kubectl
        run: |
          echo "${{ secrets.LINODE_KUBECONFIG }}" > kubeconfig.yaml
          kubectl config view --raw > kubeconfig-merged.yaml
          KUBECONFIG=kubeconfig.yaml:kubeconfig-merged.yaml kubectl config use-context config
          
      - name: Apply Kubernetes deployment
        run: kubectl apply -f deployment.yaml

      - name: Apply Kubernetes service
        run: kubectl apply -f service.yaml
