name: Deploy to Linode Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Linode cli
        uses: brendon1555/setup-linode-cli@master
        with:
          LINODE_CLI_TOKEN: ${{ secrets.LINODE_API_TOKEN }}
      - run: linode-cli --help

      - name: Deploy to Linode
        env:
          LINODE_KUBECONFIG: ${{ secrets.LINODE_KUBECONFIG }}
        run: |
          linode-cli k8s context switch --kubeconfig $LINODE_KUBECONFIG
          kubectl apply -f deployment.yaml
      - name: Apply Kubernetes service
        env:
          LINODE_KUBECONFIG: ${{ secrets.LINODE_KUBECONFIG }}
        run: |
          linode-cli k8s context switch --kubeconfig $LINODE_KUBECONFIG
          kubectl apply -f service.yaml 
