name: Deploy to Linode Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Linode CLI
        run: |
          pip3 install linode-cli --upgrade

      - name: Set Linode CLI token
        run: |
          echo "export LINODE_CLI_TOKEN=${{ secrets.LINODE_API_TOKEN }}" >> $GITHUB_ENV

      - name: Configure kubectl
        uses: engineerd/setup-kubectl@v1
        with:
          version: latest
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}

      - name: Set image tag
        id: vars
        run: |
          echo ::set-output name=IMAGE_TAG::$(echo $GITHUB_SHA)

      - name: Update Kubernetes deployment
        run: |
          kubectl set image deployment/myapp-deployment myapp-container=myusername/myapp:${{ steps.vars.outputs.IMAGE_TAG }}

      - name: Apply Kubernetes service
        run: kubectl apply -f service.yaml
